apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ssadcloudk8s-9d06"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ssadcloudk8s-9d06"
  template:
    metadata:
      labels:
        app: "ssadcloudk8s-9d06"
    spec:
      containers:
        - name: "ssadcloudk8s-9d06"
          image: "ssadcloudacr3.azurecr.io/ssadcloudk8s"
          ports:
          - containerPort: 80