apiVersion: v1
kind: Service
metadata:
    name: "ssadcloudk8s-1738"
    labels:
        app: "ssadcloudk8s-1738"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ssadcloudk8s-1738"