on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n ssadcloudacr -g ssadcloudacrb841-rg --location "East US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n ssadcloudacr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n ssadcloudacr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n ssadcloudacr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: ssadcloudacr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ssadcloudacr.azurecr.io/ssadcloudk8s:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push ssadcloudacr.azurecr.io/ssadcloudk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_ssadcloudk8s_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ssadcloudk8sb986 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ssadcloudk8sb986`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ssadcloudk8sb986
        container-registry-url: ssadcloudacr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: ssadcloudk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ssadcloudk8sb986
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          ssadcloudacr.azurecr.io/ssadcloudk8s:${{ github.sha }}
        imagepullsecrets: |
          ssadcloudk8sdockerauth   
